/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IngresoView.java
 *
 * 
 */

package view;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.*;
import control.*;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Administrador
 */
public class IngresoView extends javax.swing.JFrame {
    private Persona persona;
    private JLabel lblFoto;

    /** Creates new form IngresoView */
    public IngresoView() {
        initComponents();
        
        persona= new Persona();
              
        this.setLocationRelativeTo(null);

        
        jLabel5.setIcon(new javax.swing.ImageIcon("fotos\\foto5.jpg"));
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfRut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfFono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfFoto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESO DE DATOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 26, -1, -1));

        jButton1.setText("Grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 222, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 222, -1, -1));

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 222, -1, -1));

        jLabel2.setText("Rut:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, -1, -1));

        jtfRut.setColumns(10);
        jtfRut.setToolTipText("Ingresar rut con guión y digito verificador");
        jtfRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfRutKeyTyped(evt);
            }
        });
        getContentPane().add(jtfRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 86, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jtfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNombreFocusLost(evt);
            }
        });
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });
        getContentPane().add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 200, -1));

        jLabel4.setText("Fono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jtfFono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfFonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfFonoFocusLost(evt);
            }
        });
        jtfFono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFonoActionPerformed(evt);
            }
        });
        jtfFono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFonoKeyTyped(evt);
            }
        });
        getContentPane().add(jtfFono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 86, -1));

        jLabel5.setText("<  foto  >");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 26, 255, 255));

        jLabel6.setText("Foto:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jtfFoto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFotoKeyTyped(evt);
            }
        });
        getContentPane().add(jtfFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
          if(!jtfRut.getText().equals(""))
          {  
            persona=new Persona(jtfRut.getText(),jtfNombre.getText(),
                                 jtfFono.getText(),jtfFoto.getText());
            try {
                PersonaDB.agregar(persona);
                limpiar();
            } catch (Exception ev) {
                //Logger.getLogger(IngresoView.class.getName()).log(Level.SEVERE, null, ex);
                if(ev.getMessage().equals("Error_RUT"))
               JOptionPane.showMessageDialog(null, "ERROR  con el formato del rut...");
                
            }
          }
          else
              JOptionPane.showMessageDialog(null, "Registro en blanco...");
        }
        catch(Exception ev)
        {
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Metodo que permite consultar
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
       
         
      if(!jtfRut.getText().equals(""))
      {     
        try
        {
             persona=PersonaDB.buscar(jtfRut.getText());
             
             if(!(persona.getRut()==null))
                 actualizar();
             else
                 limpiar();
          
        } catch (Exception ev) {
            //Logger.getLogger(IngresoView.class.getName()).log(Level.SEVERE, null, ex);
               
            
        }
      }
      else
           JOptionPane.showMessageDialog(null, "Registro en blanco...");

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
      
      if(!jtfRut.getText().equals(""))
      {  
        
        String respuesta = String.valueOf(JOptionPane.showConfirmDialog(this,"¿Está Seguro que desea eliminar este registro","¿Segur@ de Eliminar?",JOptionPane.YES_NO_OPTION ));
        if(respuesta.equals( String.valueOf(JOptionPane.YES_OPTION )) )
        {
                      
           try {
                  PersonaDB.eliminar(jtfRut.getText());
                  limpiar();
               } catch (Exception ex) {
                      Logger.getLogger(IngresoView.class.getName()).log(Level.SEVERE, null, ex);
                 }
            
        }
      }
      else
           JOptionPane.showMessageDialog(null, "Registro en blanco...");
        
 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
          if(!jtfRut.getText().equals(""))
          {    
            persona=new Persona(jtfRut.getText(),jtfNombre.getText(),
                                jtfFono.getText(),jtfFoto.getText());
            try
            {
                PersonaDB.modificar(persona);
                limpiar();
            } catch (Exception ex) {
                Logger.getLogger(IngresoView.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
          else
              JOptionPane.showMessageDialog(null, "Registro en blanco...");


        }
        catch(Exception ev)
        {

        }

      
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombreFocusGained
        // TODO add your handling code here:
        jtfNombre.setBackground(Color.yellow);
    }//GEN-LAST:event_jtfNombreFocusGained

    private void jtfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombreFocusLost
        // TODO add your handling code here:
        jtfNombre.setBackground(Color.white);
    }//GEN-LAST:event_jtfNombreFocusLost

    private void jtfRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRutKeyTyped
        // TODO add your handling code here:
        //System.out.println(evt.getKeyChar());
        if( !(evt.getKeyChar()>=48 && evt.getKeyChar()<=57 || evt.getKeyChar()=='-' || 
                evt.getKeyChar()=='k'  ||  evt.getKeyChar()=='K'))
        {
           evt.consume();
        }   
        if(jtfRut.getText().length()>=10)
            evt.consume();
    }//GEN-LAST:event_jtfRutKeyTyped

    private void jtfFonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfFonoFocusGained
        // TODO add your handling code here:
        jtfFono.setBackground(Color.yellow);
    }//GEN-LAST:event_jtfFonoFocusGained

    private void jtfFonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfFonoFocusLost
        // TODO add your handling code here:
        jtfFono.setBackground(Color.white);
    }//GEN-LAST:event_jtfFonoFocusLost

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped
        // TODO add your handling code here:
        
        if( !(evt.getKeyChar()>=65 && evt.getKeyChar()<=90 ||
                evt.getKeyChar()>=97 && evt.getKeyChar()<=122 ))
        {
           evt.consume();
        }  
        
        if(jtfNombre.getText().length()>=20)
            evt.consume();
    }//GEN-LAST:event_jtfNombreKeyTyped

    private void jtfFonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFonoActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jtfFonoActionPerformed

    private void jtfFonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFonoKeyTyped
        // TODO add your handling code here:
        
        if( !(evt.getKeyChar()>=48 && evt.getKeyChar()<=57 || evt.getKeyChar()=='+' ))
        {
           evt.consume();
        } 
        
        
        if(jtfFono.getText().length()>=10)
            evt.consume();
    }//GEN-LAST:event_jtfFonoKeyTyped

    private void jtfFotoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFotoKeyTyped
        // TODO add your handling code here:
        
        
        if(jtfFoto.getText().length()>=20)
            evt.consume();
    }//GEN-LAST:event_jtfFotoKeyTyped





   public void actualizar (){
        
       // JOptionPane.showMessageDialog(null,"Act"+persona.toString());
        jtfRut.setText(persona.getRut());
        jtfNombre.setText(persona.getNombre());
        jtfFono.setText(persona.getFono());
        jtfFoto.setText(persona.getFoto());
        if(!persona.getFoto().equals(""))
            jLabel5.setIcon(new javax.swing.ImageIcon("fotos\\"+persona.getFoto()));
        //super.setVisible(true);
        //
        
   }
   
  public void limpiar(){
        jtfRut.setText("");
        jtfNombre.setText("");
        jtfFono.setText("");
        jtfFoto.setText("");
        setVisible(true);
       
  }

  public static void main(String[] arg ){

     new IngresoView().setVisible(true);
  }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jtfFono;
    private javax.swing.JTextField jtfFoto;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfRut;
    // End of variables declaration//GEN-END:variables

}
